language: python

sudo: true

services:
  - redis

python:
  # - "2.6"
  # - "2.7"
  # - "3.2"
  # - "3.3"
  # - "3.4"
  - "3.5"
  # - "3.5-dev" # 3.5 development branch
  # - "nightly" # currently points to 3.6-dev

install:
  - pip install --upgrade pip #[他預先的 pip 版本不是最新的，所以先更新一下]
  - pip install -q Flask

matrix:
    fast_finish: true

script:
    - python main.py test

notifications:
  email:
    recipients:
      - john987john987@gmail.com
    on_success: always
    on_failure: always